#!/bin/sh

# run as root
wifi_name="$(cat /home/kpm/txt/home_wifi_name)"
wifi_pass="$(cat /home/kpm/txt/home_wifi_pass)"

ifconfig lo0 down
ifconfig em0 down

ifconfig iwm0 up
ifconfig iwm0 nwid "$wifi_name" wpakey "$wifi_pass"
dhclient iwm0

