#!/bin/sh
#
# converts between currencies using rate.sx
# 
# krzysckh 2022
# krzysckh.org

from="USD"
to="PLN"
amount="1"

usage() {
  cat<<EOF
usage: $0 [-h] [-f currency] [-t currency] amount
-f (from) is USD by default
-t (to) is PLN by default
amount is 1 by default
EOF
  exit 1
}

while [ "$#" -gt 0 ]
do
  case "$1" in
    -f)
      from="$(echo $2 | tr A-Z a-z)"
      shift
      ;;
    -t)
      to="$(echo $2 | tr a-z A-Z)"
      shift
      ;;
    -h)
      usage
      ;;
    *)
      amount="$1"
      ;;
  esac
  shift
done

curl "$to".rate.sx/"$amount""$from" 2>/dev/null \
  | xargs -I '{}' echo '{}' "$to"
