#!/bin/sh

/opt/discord/Discord \
	--ignore-gpu-blocklist \
	--disable-features=UseOzonePlatform \
	--enable-features=VaapiVideoDecoder \
	--use-gl=desktop \
	--enable-gpu-rasterization \
	--enable-zero-copy \
	$@
