#!/bin/sh

# runs dmenu with colors and font set
# on my OpenBSD laptop dmenu is started mainly via dwm, but...
#
# krzysckh 2021, 2022, 2023, 2024
# krzysckh.org

case `uname` in
  OpenBSD)
      dmenu -fn "Lilex:size=7" -nb "#2b3339" -nf "#d3c6aa" \
        -sb "#d3c6aa" -sf "#282a36" "$@"
    ;;
  *)
      dmenu -fn "Lilex:pixelsize=14" -nb "#2b3339" -nf "#d3c6aa" \
        -sb "#d3c6aa" -sf "#282a36" "$@"
    ;;
esac

