#!/bin/sh

# runs dmenu with colors and font set
# on my OpenBSD laptop dmenu is started mainly via dwm, but...
#
# krzysckh 2021, 2022, 2023
# krzysckh.org

case `uname` in
  OpenBSD)
      dmenu -fn 'Lilex:size=7' -nb '#eeeeee' -nf '#101010' \
        -sb '#101010' -sf '#eeeeee' "$@"
    ;;
  *)
      dmenu -fn "agave Nerd Font:pixelsize=14" -nb "#2b3339" -nf "#d3c6aa" \
        -sb "#d3c6aa" -sf "#282a36" "$@"
    ;;
esac

