#!/bin/sh

# runs dmenu with colors and font set
# on my OpenBSD laptop dmenu is started mainly via dwm, but...
#
# krzysckh 2021, 2022
# krzysckh.org

case `uname` in
  OpenBSD)
      dmenu -fn 'agave Nerd Font:size=8' -nb '#282a36' -nf '#f8f8f2' \
        -sb '#f8f8f2' -sf '#282a36'
    ;;
  *)
      dmenu -fn "CozetteVector:pixelsize=14" -nb "#222222" -nf "#dedede" \
        -sb "#e4f614" -sf "#222222" "$@"
    ;;
esac

