#!/bin/sh
#
# dmenu emoji selecting script
# needs emoji list in $HOME/res/
# you can get it from https://github.com/krzysckh/darkrice
# 
# krzysckh 2021
# krzysckh.org

case "$(uname)" in
	*OpenBSD*)
		dmenu \
			-fn 'agave Nerd Font:size=8' \
			-nb '#000000' \
			-nf '#ffffff' \
			-sb '#ffffff' \
			-sf '#000000' \
			-l 10
		;;
	*)
		dmenu_c \
			-l 10 \
			-fn 'CozetteVector:pixelsize=14,Symbola:pixelsize=14'
		;;
esac < "$HOME"/res/emoji \
	| awk '{ print $1 }' \
	| tr -d '\n' \
	| xclip -selection clipboard
