#!/usr/bin/python3

import sys
import os
from ImageGoNord import GoNord

if len(sys.argv) < 2:
    print("usage: gocol /path/to/image > image.png")
    exit(1)

colorscheme = {
    "#2b3339",
    "#323c41",
    "#3a454a",
    "#445055",
    "#4c555b",
    "#53605c",
    "#503946",
    "#4e3e43",
    "#404d44",
    "#394f5a",
    "#4a4940",
    "#d3c6aa",
    "#e67e80",
    "#e69875",
    "#dbbc7f",
    "#a7c080",
    "#83c092",
    "#7fbbb3",
    "#d699b6",
    "#7a8478",
    "#859289",
    "#9da9a0",
    "#a7c080",
    "#d3c6aa",
    "#e67e80",
}

g_col = GoNord()
g_col.reset_palette()

for col in colorscheme:
    g_col.add_color_to_palette(col)

img = g_col.open_image(sys.argv[1])

g_col.convert_image(img, ("/tmp/gocol.png"))

os.system("/bin/cat /tmp/gocol.png")

# just print it to stdout so it can get piped
# print(f.read("...")) didnt work 'cause
# python NEEDS to be different
# thanks
