#!/bin/sh
#
# well

usage() {
	cat<<EOF
usage: $0 man options
ex. $0 1 turtel
ex. $0 7 ascii
EOF
	exit 1
}

[ -z "$1" ] && usage

echo "<pre><code>"
MANWIDTH=70 man "$@" | \
	col -b | \
	sed 's/</\&lt;/g' | \
	sed 's/>/\&gt;/g'
echo "</code></pre>"

