#!/bin/sh
# skrypt pokazujący najnowszy plan lekcji
# z plan.tk.krakow.pl
klasa="41"
# o41.html -> miejsce z planem 3pb

# wymaga:
#  (testowane na gnu) coreutils
#  curl
#  w3m
#  plan9port (dla htmlfmt)

usr="$(cat "$HOME"/txt/tk_usr)"
pass="$(cat "$HOME"/txt/tk_pass)"


curl --user "$usr":"$pass" https://plan.tk.krakow.pl 2>/dev/null \
	| htmlfmt \
	| awk '(NR>2)' \
	| tr '.' ' ' \
	| awk '{ printf "%02d%02d%02d\n", $3, $2, $1 }' \
	| sort -n \
	| tail -n 1 \
	| sed 's/./&\ /4 ; s/./&\ /7' \
	| awk '{ printf "%02d.%02d.%02d", $3, $2, $1 }' \
	| xargs -I '{}' \
		w3m -cols "$(tput cols)" -dump \
		http://"$usr":"$pass"@plan.tk.krakow.pl/'{}'/plany/o"$klasa".html

#curl --user "$usr":"$pass" \
#http://plan.tk.krakow.pl/'{}'/plany/o"$klasa".html 2>/dev/null \
#> /tmp/plan.html

