#!/bin/sh
# sends file to img.krzysckh.org
# lol
# 
# krzysckh 2022
# krzysckh.org

fname=
date=

die() {
  echo $@
  exit 1
}

while [ "$#" -gt 0 ]
do
  case "$1" in
    -d)
      date="$2"
      shift
      ;;
    *)
      fname="$1"
      ;;
  esac
  shift
done

[ -z "$fname" ] && die "debil."
[ -z "$date" ] && {
  echo "zbieranie danych z $fname"
  date="`stat -r "$fname" | cut -f9 -d' '`"
}

echo "napewno? $fname ($date = `perl -e "print scalar localtime $date"`)"
printf '[y/n] '
read yn

if [ "$yn" = 'y' ]; then
  convert "$fname" -quality 100 /tmp/"$date.jpg" || die "problem magick"
	sshpass \
    -P 'Enter passphrase for key' \
    -p $(cat $HOME/txt/pas_krzorg) \
    scp -i $HOME/.ssh/krzysckh.org /tmp/"$date.jpg" \
    scp://root@krzysckh.org//var/www/pub/img/"$date.jpg"
fi

echo "https://pub.krzysckh.org/img/$date.jpg"

