#!/bin/sh

if [ -e "$HOME/Documents" ]; then
	bakf="$HOME/Documents/srv_bak"
else
	bakf="$HOME/documents/srv_bak"
fi

for serv in "krzysckh.org" "pub.krzysckh.org"
do
	sshpass \
		-P 'Enter passphrase for key' \
		-p "$(cat $HOME/txt/pas_krzorg)" \
		ssh -i "$HOME/.ssh/krzysckh.org" \
		"root@$serv" \
		"sh crbak.sh"

	fname="`date +%s`_bak-$serv.tgz"

	sshpass \
		-P 'Enter passphrase for key' \
		-p $(cat $HOME/txt/pas_krzorg) \
		scp -i "$HOME/.ssh/krzysckh.org" \
		scp://root@$serv//root/bak.tgz \
		"$bakf/$fname"
done
