#!/bin/sh

# dwm bar script
#
# krzysckh 2021, 2022
# krzysckh.org

datetime() {
	date +"%d/%m/%y, %H:%M" | tr -d '\n'
}

sound() {
	amixer get Master | tail -n 1 | awk '{print $5}' | tr -d '%'
}

while :
do
	info=" snd: $(sound), d: $(datetime)"
	xsetroot -name "$info"
	sleep 2
done
