#!/bin/sh

# script to generate and set wallpaper for my rice and colorscheme B)
# 
# krzysckh 2021, 2023
# krzysckh.org

usage() {
	echo "usage: $0 /path/to/image.png [left / right]"
	exit 1
}

[ -z "$1" ] && usage

screen_x=1920
screen_y=1200

place_opts="-gravity center"

img_x=$(convert $1 -format "%[w]" info:)
img_y=$(convert $1 -format "%[h]" info:)

[ "$2" = "left" ] && \
	place_opts="-geometry +$(($screen_x/10))+$((($screen_y-$img_y)/2))"

[ "$2" = "right" ] && \
	place_opts="-geometry +$((($screen_x-$img_x)-($screen_x/10)))+$((($screen_y-$img_y)/2))"

gwall "#2b3339" "#445055" 5

convert -size "$screen_x"x"$screen_y" tile:/tmp/wall.png /tmp/w.png
convert "$1" -monochrome +level-colors "#2b3339","#d3c6aa","#d3c6aa" /tmp/k.png
composite $place_opts /tmp/k.png -bordercolor "#d3c6aa" -border 1x1 /tmp/w.png /tmp/new-wal.png

xwallpaper --center /tmp/new-wal.png
