#!/bin/sh
#
# run mpv on youtuibe lin /w highest quality
# i use it as a link handler for ytfzf

usage() {
	echo "usage: $0 link.to/video"
	exit 1
}

[ -z "$1" ] && usage
link=$1
shift

yt-dlp -f bestvideo+bestaudio/best "$link" -o - | mpv "$@" -

