#!/bin/sh
#
# run mpv on youtube link /w highest quality
# i use it as a link handler for ytfzf

usage() {
	echo "usage: $0 link.to/video"
	exit 1
}

[ -z "$1" ] && usage
L=$1
shift

case $L in
  http*) ;;
  *) L="ytsearch1:$L" ;;
esac

yt-dlp -f bestvideo+bestaudio/best "$L" -o - | mpv "$@" -

