#!/usr/bin/perl
# -*- mode: cperl; cperl-indent-level: 2 -*-
# script for my dwm build. launches a youtube video from a link in the clipboard
#
# krzysckh 2023
# krzysckh.org

use strict;
use warnings;

sub Try {
  ($_) = @_;

  if (m!^https?://.*/watch\?v=[a-zA-Z0-9\_\-\+\=]+$!) {
    if (fork) {
      `mpv $_`;
      exit 0
    } else {
      `notify-send "ytclip" "ok"`;
      exit 0
    }
  }
}

# https://unix.stackexchange.com/questions/629440/how-to-get-the-url-from-current-tab-of-firefox-without-need-to-install-addition
sub Fromff {
  my $wid=`xdotool search --onlyvisible --class "firefox"`;
  `xdotool key --window "$wid" --delay 20 --clearmodifiers ctrl+l ctrl+c Escape`;
  Try `xclip -o -selection clipboard`
}

Fromff;
Try `xclip -sel p -o`;
Try `xclip -sel c -o`;

`notify-send "ytclip" "fatal"`
