#!/usr/bin/perl
#
# script for my dwm build. launches a youtube video from a link in the clipboard
# via the `yt` script.
#
# krzysckh 2023
# krzysckh.org

use strict;
use warnings;

sub Try {
  ($_) = @_;

  if (m!^https?://.*/watch\?v=[a-zA-Z0-9\_\-\+\=]+$!) {
    if (fork) {
      `yt $_`;
      exit 0
    } else {
      `notify-send "ytclip" "ok"`;
      exit 0
    }
  }
}

Try `xclip -sel c -o`;
Try `xclip -sel p -o`;

`notify-send "ytclip" "fatal"`
